# DELHI_NCR AQI ML MODEL

DATA HANDLING

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('delhi_ncr_aqi_dataset.csv')
df

,datetime,date,year,month,day,hour,day_of_week,is_weekend,season,city,...,no2,so2,co,o3,temperature,humidity,wind_speed,visibility,aqi,aqi_category
0,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,119.6,47.7,5.19,12.3,9.4,100,3.6,1.2,500,Severe
1,2020-01-01 12:00:00,2020-01-01,2020,1,1,12,Wednesday,0,winter,Delhi,...,117.9,39.3,4.32,15.8,20.6,50,5.9,1.4,500,Severe
2,2020-01-01 18:00:00,2020-01-01,2020,1,1,18,Wednesday,0,winter,Delhi,...,150.1,36.3,7.13,14.3,12.4,56,4.5,1.1,500,Severe
3,2020-01-01 23:00:00,2020-01-01,2020,1,1,23,Wednesday,0,winter,Delhi,...,142.0,30.3,4.90,13.2,14.4,48,5.8,1.4,500,Severe
4,2020-01-01 06:00:00,2020-01-01,2020,1,1,6,Wednesday,0,winter,Delhi,...,138.4,41.5,7.56,15.4,6.8,100,2.8,0.4,500,Severe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201659,2025-12-31 23:00:00,2025-12-31,2025,12,31,23,Wednesday,0,winter,Ghaziabad,...,97.0,23.9,5.58,14.8,16.1,51,3.8,0.9,500,Severe
201660,2025-12-31 06:00:00,2025-12-31,2025,12,31,6,Wednesday,0,winter,Ghaziabad,...,119.2,26.9,5.34,12.1,9.8,95,3.2,1.2,500,Severe
201661,2025-12-31 12:00:00,2025-12-31,2025,12,31,12,Wednesday,0,winter,Ghaziabad,...,90.3,33.7,3.73,28.2,21.4,57,7.1,2.9,500,Severe
201662,2025-12-31 18:00:00,2025-12-31,2025,12,31,18,Wednesday,0,winter,Ghaziabad,...,170.7,20.9,6.98,22.9,15.4,51,6.8,1.2,500,Severe
201663,2025-12-31 23:00:00,2025-12-31,2025,12,31,23,Wednesday,0,winter,Ghaziabad,...,89.0,27.5,5.17,17.6,17.3,46,5.4,1.0,500,Severe

In [3]:
df['aqi_category'].unique()

array(['Severe', 'Very Poor', 'Poor', 'Moderate', 'Satisfactory', 'Good'],
      dtype=object)

In [4]:
df['season'].unique()

array(['winter', 'summer', 'monsoon', 'post_monsoon'], dtype=object)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201664 entries, 0 to 201663
Data columns (total 25 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   datetime      201664 non-null  object
 1   date          201664 non-null  object
 2   year          201664 non-null  int64
 3   month         201664 non-null  int64
 4   day           201664 non-null  int64
 5   hour          201664 non-null  int64
 6   day_of_week   201664 non-null  object
 7   is_weekend    201664 non-null  int64
 8   season        201664 non-null  object
 9   city          201664 non-null  object
 10  station       201664 non-null  object
 11  latitude      201664 non-null  float64
 12  longitude     201664 non-null  float64
 13  pm25          201664 non-null  float64
 14  pm10          201664 non-null  float64
 15  no2           201664 non-null  float64
 16  so2           201664 non-null  float64
 17  co            201664 non-null  float64
 18  o3            201664 non-null  float64
 19  temperature   201664 non-null  float64
 20  humidity      201664 non-null  int64
 21  wind_speed    201664 non-null  float64
 22  visibility    201664 non-null  float64
 23  aqi           201664 non-null  int64
 24  aqi_category  201664 non-null  object
dtypes: float64(11), int64(7), object(7)
memory usage: 38.5+ MB

In [6]:
df['datetime'] = pd.to_datetime(df['datetime'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201664 entries, 0 to 201663
Data columns (total 25 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   datetime      201664 non-null  datetime64[ns]
 1   date          201664 non-null  object
 2   year          201664 non-null  int64
 3   month         201664 non-null  int64
 4   day           201664 non-null  int64
 5   hour          201664 non-null  int64
 6   day_of_week   201664 non-null  object
 7   is_weekend    201664 non-null  int64
 8   season        201664 non-null  object
 9   city          201664 non-null  object
 10  station       201664 non-null  object
 11  latitude      201664 non-null  float64
 12  longitude     201664 non-null  float64
 13  pm25          201664 non-null  float64
 14  pm10          201664 non-null  float64
 15  no2           201664 non-null  float64
 16  so2           201664 non-null  float64
 17  co            201664 non-null  float64
 18  o3            201664 non-null  float64
 19  temperature   201664 non-null  float64
 20  humidity      201664 non-null  int64
 21  wind_speed    201664 non-null  float64
 22  visibility    201664 non-null  float64
 23  aqi           201664 non-null  int64
 24  aqi_category  201664 non-null  object
dtypes: datetime64[ns](1), float64(11), int64(7), object(6)
memory usage: 38.5+ MB

In [7]:
df['city'].unique()

array(['Delhi', 'Noida', 'Gurugram', 'Faridabad', 'Ghaziabad'],
      dtype=object)

ENCODING DATA

In [8]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
stan = StandardScaler()
la_season = LabelEncoder()
la_city = LabelEncoder()
la_aqi_category = LabelEncoder()
df['city_encoded'] = la_city.fit_transform(df['city'])
df['season_encoded'] = la_season.fit_transform(df['season'])
df['aqi_category_encoded'] = la_aqi_category.fit_transform(df['aqi_category'])
df['datetime'] = df['datetime'].astype('int64')
df['datetime'] = stan.fit_transform(df[['datetime']])

In [9]:
df['city'].unique()

array(['Delhi', 'Noida', 'Gurugram', 'Faridabad', 'Ghaziabad'],
      dtype=object)

In [10]:
df[['city','city_encoded']].drop_duplicates().sort_values('city_encoded')

         city  city_encoded
0       Delhi             0
76  Faridabad             1
84  Ghaziabad             2
68   Gurugram             3
56      Noida             4

In [11]:
df[['season','season_encoded']].drop_duplicates().sort_values('season_encoded')

             season  season_encoded
13984       monsoon               0
25208  post_monsoon               1
5520         summer               2
0            winter               3

In [12]:
df[['aqi_category','aqi_category_encoded']].drop_duplicates().sort_values('aqi_category_encoded')

       aqi_category  aqi_category_encoded
14049          Good                     0
5541       Moderate                     1
5521           Poor                     2
8481   Satisfactory                     3
0            Severe                     4
5         Very Poor                     5

In [13]:
df['datetime']

0        -1.731837
1        -1.731442
2        -1.731047
3        -1.730717
4        -1.731837
            ...
201659    1.731804
201660    1.730685
201661    1.731080
201662    1.731475
201663    1.731804
Name: datetime, Length: 201664, dtype: float64

In [14]:
df['season'].unique()

array(['winter', 'summer', 'monsoon', 'post_monsoon'], dtype=object)

In [15]:
df['aqi_category'].unique()

array(['Severe', 'Very Poor', 'Poor', 'Moderate', 'Satisfactory', 'Good'],
      dtype=object)

MODEL FITTING

In [16]:
from sklearn.linear_model import LogisticRegression
X = df[['datetime','is_weekend','season_encoded','city_encoded','no2','so2','co','o3','temperature','humidity','wind_speed','visibility','aqi']]
y = df['aqi_category_encoded']
model = LogisticRegression()
model.fit(X,y)

c:\Users\WELCOME\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

MODEL PREDICTION

In [17]:
datetime = input('enter datetime (YYYY-MM-DD TT:TT:TT): ')
datetime = (pd.to_datetime(datetime)).value
datetime = stan.transform([[datetime]])
datetime = datetime[0][0]
season = int(input("enter the season in no:" \
"for winter: 3" \
"for post_monsoon: 1" \
"for monsoon: 0" \
"for summer: 2" \
"enter: "))
city = int(input("enter the city in no:" \
"for faridabad: 1" \
"for delhi: 0" \
"for ghaziabad: 2" \
"for gurugram: 3" \
"for noida: 4" \
"enter : "))
is_weekend = int(input('is there a weekend that day:'))
no2 = float(input('enter no2: '))
so2 = float(input('enter so2:'))
co = float(input('enter co:'))
o3 = float(input('enter o3:'))
temperature = float(input('enter the temperature: '))
humidity = float(input('enter humidity'))
wind_speed = float(input('enter wind speed: '))
visibility = float(input('enter visibility: '))
aqi = float(input('enter aqi:'))
answer = model.predict([[datetime,is_weekend,season,city,no2,so2,co,o3,temperature,humidity,wind_speed,visibility,aqi]])
answer

c:\Users\WELCOME\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
c:\Users\WELCOME\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([4])

In [24]:
answered = answer[0]
answered

np.int64(4)

In [25]:
answered_category = df[df['aqi_category_encoded']==answered]['aqi_category'].drop_duplicates()

In [32]:
answered_category= answered_category[0]

In [33]:
print(f'final answer is your city air is in {answered_category} condition')

final answer is your city air is in Severe condition